WITH RECURSIVE
    UNDER_ROLE(NAME,PARENT,DESCRIPTION,ID) AS (
        SELECT '' AS NAME, 0 AS PARENT, '' AS DESCRIPTION, 0 AS ID
        UNION ALL
        SELECT ACL_ROLES.NAME, UNDER_ROLE.PARENT + 1, ACL_ROLES.DESCRIPTION, ACL_ROLES.ID
            FROM ACL_ROLES JOIN UNDER_ROLE ON ACL_ROLES.PARENT=UNDER_ROLE.PARENT
            WHERE ACL_ROLES.ACTIVE = 1
            ORDER BY 2
    )
SELECT
    UNDER_ROLE.ID AS ROLE_ID,
    UNDER_ROLE.NAME AS ROLE_NAME,
    UNDER_ROLE.DESCRIPTION AS ROLED_ESCRIPTION,
    ACL_PERMISSIONS.ID AS PERMISSION_ID,
    ACL_PERMISSIONS.NAME AS PERMISSION_NAME,
    ACL_PERMISSIONS.DESCRIPTION AS PERMISSION_DESCRIPTION
    FROM UNDER_ROLE
    JOIN ACL_ROLEPERMISSIONS ON UNDER_ROLE.ID = ACL_ROLEPERMISSIONS.ROLEID
    JOIN ACL_PERMISSIONS ON ACL_ROLEPERMISSIONS.PERMISSIONID = ACL_PERMISSIONS.ID
    WHERE UNDER_ROLE.PARENT > 0
    AND ACL_PERMISSIONS.ACTIVE = 1;
