CREATE TABLE ACL_USERS(
	ID          INTEGER     PRIMARY KEY AUTOINCREMENT,
	USERNAME    TEXT        NOT NULL,
	PASSWORD    TEXT        NOT NULL,
	EMAIL       TEXT        NOT NULL,
	FULLNAME    TEXT        NULL,
	TYPE        CHAR(10)    NULL,
	CREATED     INTEGER     NOT NULL,
	MODIFIED    INTEGER     NOT NULL,
	ACTIVE      INTEGER     NOT NULL,
	CONSTRAINT U_USER_NAME UNIQUE (USERNAME) ON CONFLICT FAIL,
	CONSTRAINT U_USER_EMAIL UNIQUE (EMAIL) ON CONFLICT FAIL
);

CREATE TABLE ACL_ROLES(
	ID          INTEGER     PRIMARY KEY AUTOINCREMENT,
	NAME        TEXT        NOT NULL,
	DESCRIPTION TEXT        NOT NULL,
	PARENT      INTEGER     NULL,
	CREATED     INTEGER     NOT NULL,
	MODIFIED    INTEGER     NOT NULL,
	DELETABLE   INTEGER     NULL,
	ACTIVE      INTEGER     NOT NULL,
	CONSTRAINT U_ROLE_NAME UNIQUE (NAME)  ON CONFLICT FAIL
);

CREATE TABLE ACL_PERMISSIONS(
    ID          INTEGER     PRIMARY KEY AUTOINCREMENT,
    NAME        TEXT        NOT NULL,
    DESCRIPTION TEXT        NOT NULL,
    PARENT      INTEGER     NULL,
    CREATED     INTEGER     NOT NULL,
    MODIFIED    INTEGER     NOT NULL,
    DELETABLE   INTEGER     NULL,
    ACTIVE      INTEGER     NOT NULL,
    CONSTRAINT U_PERMISSION_NAME UNIQUE (NAME)  ON CONFLICT FAIL
);

CREATE TABLE ACL_ROLEPERMISSIONS(
    ROLEID       INTEGER     NOT NULL,
    PERMISSIONID INTEGER     NOT NULL,
    CREATED      INTEGER     NOT NULL,
    MODIFIED     INTEGER     NOT NULL,
    ACTIVE       INTEGER     NOT NULL,
    PRIMARY KEY (ROLEID, PERMISSIONID)
);

CREATE TABLE ACL_USERROLES(
    USERID      INTEGER     NOT NULL,
    ROLEID      INTEGER     NOT NULL,
    CREATED     INTEGER     NOT NULL,
    MODIFIED    INTEGER     NOT NULL,
    ACTIVE      INTEGER     NOT NULL,
    PRIMARY KEY (USERID, ROLEID)
);
