CREATE VIEW V_UNDER_PERMISSION AS
    WITH RECURSIVE
        UNDER_PERMISSION(NAME,PARENT,DESCRIPTION,ID) AS (
            SELECT '' AS NAME, 0 AS PARENT, '' AS DESCRIPTION, 0 AS ID
            UNION ALL
            SELECT ACL_PERMISSIONS.NAME, UNDER_PERMISSION.PARENT + 1, ACL_PERMISSIONS.DESCRIPTION, ACL_PERMISSIONS.ID
                FROM ACL_PERMISSIONS JOIN UNDER_PERMISSION ON ACL_PERMISSIONS.PARENT=UNDER_PERMISSION.ID
                WHERE ACL_PERMISSIONS.ACTIVE = 1
                ORDER BY 2 DESC
        )
    SELECT ID, NAME, PARENT, DESCRIPTION FROM UNDER_PERMISSION WHERE PARENT > 0;

CREATE VIEW V_UNDER_ROLE AS
    WITH RECURSIVE
        UNDER_ROLE(NAME,PARENT,DESCRIPTION,ID) AS (
            SELECT '' AS NAME, 0 AS PARENT, '' AS DESCRIPTION, 0 AS ID
            UNION ALL
            SELECT ACL_ROLES.NAME, UNDER_ROLE.PARENT + 1, ACL_ROLES.DESCRIPTION, ACL_ROLES.ID
                FROM ACL_ROLES JOIN UNDER_ROLE ON ACL_ROLES.PARENT=UNDER_ROLE.ID
                WHERE ACL_ROLES.ACTIVE = 1
                ORDER BY 2 DESC
        )
    SELECT ID, NAME, PARENT, DESCRIPTION FROM UNDER_ROLE WHERE PARENT > 0;

DELETE FROM ACL_USERS;
DELETE FROM sqlite_sequence WHERE name='ACL_USERS';

DELETE FROM ACL_USERROLES;
DELETE FROM sqlite_sequence WHERE name='ACL_USERROLES';
